name: Exosphere snippets service
description: Manages snippets of text associated with data

setup: bin/setup
startup:
  command: node_modules/.bin/exo-js
  online-text: online at port

messages:
  receives:
    - snippets.create
    - snippets.list
  sends:
    - snippets.created
    - snippets.listed

needs-dependencies:
  - MongoDB

# these configuration values have to be provided
# by the runtime that uses this service
# as environment variables when starting it
external-configuration:
  - mongodb-host
  - mongodb-port
  - database-name
