name: Exosphere tweets service
description: Manages tweets in Exosphere applications

setup: npm install
startup:
  command: node_modules/.bin/exo-js
  online-text: online at port


messages:
  receives:
    - tweets.create
    - tweets.list
    - tweet.get-details
    - tweet.update
    - tweet.delete
  sends:
    - tweets.created
    - tweets.listed
    - tweet.details
    - tweet.not-found
    - tweet.updated
    - tweet.deleted
