name: Exosphere tweets service
description: Manages tweets of text associated with data

setup: bin/setup
startup:
  command: node_modules/.bin/exo-js
  online-text: online at port

messages:
  receives:
    - tweets.create
    - tweets.list
  sends:
    - tweets.created
    - tweets.listed

needs-dependencies:
  - MongoDB

# these configuration values have to be provided
# by the runtime that uses this service
# as environment variables when starting it
external-configuration:
  - mongodb-host
  - mongodb-port
  - database-name
